/**
 * Workout Renderer — Exercise Database
 * Full 100 exercise definitions with metadata for display and TTS.
 */

export type ExerciseCategory = 'lower' | 'push' | 'pull' | 'core' | 'conditioning';

export interface ExerciseInfo {
  exercise_id: string;
  name: string;
  category: ExerciseCategory;
  description: string;
  primary_muscles: string[];
  secondary_muscles: string[];
  equipment: string[];
  pro_tips: string[];
  hasAnimation: boolean; // true = real image, false = placeholder
}

export const EXERCISES: ExerciseInfo[] = [
  // ─── LOWER BODY (25) ────────────────────────────────────────────────────────
  {
    exercise_id: 'bodyweight_squat', name: 'Bodyweight Squat', category: 'lower',
    description: 'Feet shoulder-width, sit hips back and down, knees track over toes, stand tall.',
    primary_muscles: ['Quads', 'Glutes'], secondary_muscles: ['Adductors', 'Core'],
    equipment: ['Bodyweight'], pro_tips: ['Brace ribs down, keep tripod foot, avoid knees collapsing inward.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'goblet_squat', name: 'Goblet Squat', category: 'lower',
    description: 'Hold weight at chest, squat deep with upright torso, drive up through midfoot.',
    primary_muscles: ['Quads', 'Glutes'], secondary_muscles: ['Core', 'Adductors'],
    equipment: ['Kettlebell', 'Dumbbell'], pro_tips: ['Keep weight close to sternum; pause 1–2s at bottom for control.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'db_back_squat', name: 'Dumbbell Back Squat', category: 'lower',
    description: 'Use dumbbells in front rack or suitcase style; squat with stable torso and controlled depth.',
    primary_muscles: ['Quads', 'Glutes'], secondary_muscles: ['Core', 'Adductors'],
    equipment: ['Dumbbell', 'Bench'], pro_tips: ['If grip limits you, use front rack or goblet for safer loading.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'kb_front_squat', name: 'Kettlebell Front Squat', category: 'lower',
    description: 'Front rack kettlebell(s), elbows forward, squat down, stand without losing rack position.',
    primary_muscles: ['Quads', 'Glutes'], secondary_muscles: ['Core', 'Upper Back'],
    equipment: ['Kettlebell'], pro_tips: ['Keep forearms vertical; breathe and brace before each rep.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'sumo_squat', name: 'Sumo Squat', category: 'lower',
    description: 'Wide stance, toes out, sit between hips, drive knees out as you stand.',
    primary_muscles: ['Glutes', 'Adductors'], secondary_muscles: ['Quads', 'Core'],
    equipment: ['Bodyweight', 'Dumbbell', 'Kettlebell'], pro_tips: ['Keep knees tracking with toes; avoid collapsing arches.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'split_squat', name: 'Split Squat', category: 'lower',
    description: 'Stagger stance, drop back knee toward floor, front foot stable, stand through front leg.',
    primary_muscles: ['Quads', 'Glutes'], secondary_muscles: ['Adductors', 'Core'],
    equipment: ['Bodyweight', 'Dumbbell', 'Kettlebell'], pro_tips: ['Keep front heel down; control the bottom to avoid bouncing.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'bulgarian_split_squat', name: 'Bulgarian Split Squat', category: 'lower',
    description: 'Rear foot on bench, lower under control, stand by driving through front foot.',
    primary_muscles: ['Quads', 'Glutes'], secondary_muscles: ['Adductors', 'Core'],
    equipment: ['Bench', 'Bodyweight', 'Dumbbell'], pro_tips: ['Think "down and slightly forward"; keep hips square.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'reverse_lunge', name: 'Reverse Lunge', category: 'lower',
    description: 'Step back, lower until both knees bend, push through front foot to return.',
    primary_muscles: ['Glutes', 'Quads'], secondary_muscles: ['Core', 'Adductors'],
    equipment: ['Bodyweight', 'Dumbbell', 'Kettlebell'], pro_tips: ['Keep front shin relatively vertical if knees feel cranky.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'forward_lunge', name: 'Forward Lunge', category: 'lower',
    description: 'Step forward, absorb with hip and knee, push back to start.',
    primary_muscles: ['Quads', 'Glutes'], secondary_muscles: ['Core', 'Adductors'],
    equipment: ['Bodyweight', 'Dumbbell', 'Kettlebell'], pro_tips: ['Land softly; keep knee aligned with second toe.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'walking_lunge', name: 'Walking Lunge', category: 'lower',
    description: 'Alternate stepping lunges forward continuously with controlled depth.',
    primary_muscles: ['Quads', 'Glutes'], secondary_muscles: ['Calves', 'Core'],
    equipment: ['Bodyweight', 'Dumbbell', 'Kettlebell'], pro_tips: ['Stay tall through torso; avoid wobbling knee-in.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'lateral_lunge', name: 'Lateral Lunge', category: 'lower',
    description: 'Step out to side, sit hips back on working leg, push back to center.',
    primary_muscles: ['Glutes', 'Adductors'], secondary_muscles: ['Quads', 'Core'],
    equipment: ['Bodyweight', 'Dumbbell', 'Kettlebell'], pro_tips: ['Think "hinge back" not "knee forward" for stability.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'curtsy_lunge', name: 'Curtsy Lunge', category: 'lower',
    description: 'Step one leg behind and across, lower, push through front foot to return.',
    primary_muscles: ['Glutes', 'Abductors'], secondary_muscles: ['Quads', 'Core'],
    equipment: ['Bodyweight', 'Dumbbell', 'Kettlebell'], pro_tips: ['Keep hips level; don\'t let front knee collapse inward.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'step_up', name: 'Step-Up', category: 'lower',
    description: 'Step onto box/bench, drive through lead foot to stand, control descent.',
    primary_muscles: ['Glutes', 'Quads'], secondary_muscles: ['Calves', 'Core'],
    equipment: ['Box', 'Bench', 'Dumbbell'], pro_tips: ['Avoid pushing off trailing leg; keep knee tracking over toes.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'box_step_up', name: 'Box Step-Up', category: 'lower',
    description: 'Same as step-up with consistent box height and full hip extension at top.',
    primary_muscles: ['Glutes', 'Quads'], secondary_muscles: ['Core', 'Calves'],
    equipment: ['Box', 'Dumbbell'], pro_tips: ['Keep chest tall; control the down step to protect knees.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'glute_bridge', name: 'Glute Bridge', category: 'lower',
    description: 'Lie on back, feet planted, drive hips up by squeezing glutes, lower under control.',
    primary_muscles: ['Glutes'], secondary_muscles: ['Hamstrings', 'Core'],
    equipment: ['Bodyweight', 'Dumbbell'], pro_tips: ['Posterior pelvic tilt at top; squeeze glutes hard.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'single_leg_glute_bridge', name: 'Single-Leg Glute Bridge', category: 'lower',
    description: 'Same as glute bridge but one leg extended; more glute isolation.',
    primary_muscles: ['Glutes'], secondary_muscles: ['Hamstrings', 'Core'],
    equipment: ['Bodyweight'], pro_tips: ['Keep hips level; don\'t let the non-working hip drop.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'hip_thrust', name: 'Hip Thrust', category: 'lower',
    description: 'Shoulders on bench, drive hips up by squeezing glutes, full hip extension at top.',
    primary_muscles: ['Glutes'], secondary_muscles: ['Hamstrings', 'Core'],
    equipment: ['Bench', 'Bodyweight', 'Barbell'], pro_tips: ['Chin tucked, ribs down; avoid hyperextending lower back.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'db_rdl', name: 'Romanian Deadlift', category: 'lower',
    description: 'Hinge at hips, lower dumbbells along legs, feel hamstring stretch, drive hips forward.',
    primary_muscles: ['Hamstrings', 'Glutes'], secondary_muscles: ['Erectors', 'Core'],
    equipment: ['Dumbbell'], pro_tips: ['Soft knee bend; keep bar close to legs throughout.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'single_leg_rdl', name: 'Single-Leg RDL', category: 'lower',
    description: 'Balance on one leg, hinge forward with flat back, reach toward floor.',
    primary_muscles: ['Hamstrings', 'Glutes'], secondary_muscles: ['Core', 'Erectors'],
    equipment: ['Bodyweight', 'Dumbbell', 'Kettlebell'], pro_tips: ['Keep hips square; move as one unit from heel to head.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'kb_deadlift', name: 'Kettlebell Deadlift', category: 'lower',
    description: 'Hinge, grip kettlebell, brace, drive through floor to stand with hips and knees extending together.',
    primary_muscles: ['Glutes', 'Hamstrings'], secondary_muscles: ['Erectors', 'Core'],
    equipment: ['Kettlebell'], pro_tips: ['Lat engagement before pull; think "push the floor away".'],
    hasAnimation: false,
  },
  {
    exercise_id: 'sumo_deadlift', name: 'Sumo Deadlift', category: 'lower',
    description: 'Wide stance, toes out, grip inside legs, drive knees out and hips through.',
    primary_muscles: ['Glutes', 'Adductors'], secondary_muscles: ['Hamstrings', 'Erectors'],
    equipment: ['Barbell', 'Kettlebell', 'Dumbbell'], pro_tips: ['Push the floor apart; keep chest up and hips low at start.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'calf_raise', name: 'Calf Raise', category: 'lower',
    description: 'Rise onto toes, hold briefly, lower under control.',
    primary_muscles: ['Calves'], secondary_muscles: [],
    equipment: ['Bodyweight', 'Dumbbell'], pro_tips: ['Full range of motion; slow eccentric for more growth.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'single_leg_calf_raise', name: 'Single-Leg Calf Raise', category: 'lower',
    description: 'Same as calf raise on one leg for increased difficulty.',
    primary_muscles: ['Calves'], secondary_muscles: ['Core'],
    equipment: ['Bodyweight'], pro_tips: ['Hold wall for balance if needed; full stretch at bottom.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'wall_sit', name: 'Wall Sit', category: 'lower',
    description: 'Back against wall, thighs parallel to floor, hold position.',
    primary_muscles: ['Quads'], secondary_muscles: ['Glutes', 'Core'],
    equipment: ['Bodyweight'], pro_tips: ['Keep knees at 90°; don\'t let them cave inward.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'kb_swing', name: 'Kettlebell Swing', category: 'lower',
    description: 'Hip hinge power movement; drive hips forward to swing kettlebell to shoulder height.',
    primary_muscles: ['Glutes', 'Hamstrings'], secondary_muscles: ['Core', 'Lats'],
    equipment: ['Kettlebell'], pro_tips: ['It\'s a hip hinge, not a squat; snap hips at top.'],
    hasAnimation: false,
  },

  // ─── PUSH UPPER (15) ────────────────────────────────────────────────────────
  {
    exercise_id: 'push_up', name: 'Push-Up', category: 'push',
    description: 'Hands shoulder-width, lower chest to floor, press back up with full body tension.',
    primary_muscles: ['Chest', 'Triceps'], secondary_muscles: ['Front Delts', 'Core'],
    equipment: ['Bodyweight'], pro_tips: ['Elbows at 45°; keep body in straight line throughout.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'incline_push_up', name: 'Incline Push-Up', category: 'push',
    description: 'Hands on elevated surface, easier variation for beginners.',
    primary_muscles: ['Chest', 'Triceps'], secondary_muscles: ['Front Delts', 'Core'],
    equipment: ['Bodyweight', 'Bench'], pro_tips: ['Keep body straight; don\'t let hips sag.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'decline_push_up', name: 'Decline Push-Up', category: 'push',
    description: 'Feet elevated, targets upper chest more.',
    primary_muscles: ['Upper Chest', 'Triceps'], secondary_muscles: ['Front Delts', 'Core'],
    equipment: ['Bodyweight', 'Bench'], pro_tips: ['Control the descent; keep core tight.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'diamond_push_up', name: 'Diamond Push-Up', category: 'push',
    description: 'Hands close together forming diamond, heavy tricep emphasis.',
    primary_muscles: ['Triceps', 'Chest'], secondary_muscles: ['Front Delts'],
    equipment: ['Bodyweight'], pro_tips: ['Elbows track back, not out; keep wrists neutral.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'db_floor_press', name: 'Dumbbell Floor Press', category: 'push',
    description: 'Lying on floor, press dumbbells from elbow-on-floor position.',
    primary_muscles: ['Chest', 'Triceps'], secondary_muscles: ['Front Delts'],
    equipment: ['Dumbbell'], pro_tips: ['Elbows touch floor at bottom; eliminates shoulder stress.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'db_bench_press', name: 'Dumbbell Bench Press', category: 'push',
    description: 'Lying on bench, press dumbbells from chest to full extension.',
    primary_muscles: ['Chest', 'Triceps'], secondary_muscles: ['Front Delts'],
    equipment: ['Dumbbell', 'Bench'], pro_tips: ['Retract scapulae; control the eccentric.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'incline_db_press', name: 'Incline DB Press', category: 'push',
    description: 'Inclined bench press targeting upper chest.',
    primary_muscles: ['Upper Chest', 'Triceps'], secondary_muscles: ['Front Delts'],
    equipment: ['Dumbbell', 'Bench'], pro_tips: ['45° bench angle; don\'t flare elbows excessively.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'db_shoulder_press', name: 'Dumbbell Shoulder Press', category: 'push',
    description: 'Seated or standing, press dumbbells overhead from shoulder level.',
    primary_muscles: ['Front Delts', 'Side Delts'], secondary_muscles: ['Triceps', 'Upper Traps'],
    equipment: ['Dumbbell'], pro_tips: ['Brace core; avoid excessive arch in lower back.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'arnold_press', name: 'Arnold Press', category: 'push',
    description: 'Rotating press from palms-in to palms-out as you press overhead.',
    primary_muscles: ['Front Delts', 'Side Delts'], secondary_muscles: ['Triceps', 'Rear Delts'],
    equipment: ['Dumbbell'], pro_tips: ['Smooth rotation; don\'t rush the movement.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'lateral_raise', name: 'Lateral Raise', category: 'push',
    description: 'Raise dumbbells to shoulder height with slight forward lean.',
    primary_muscles: ['Side Delts'], secondary_muscles: ['Upper Traps'],
    equipment: ['Dumbbell'], pro_tips: ['Lead with elbows; slight internal rotation at top.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'front_raise', name: 'Front Raise', category: 'push',
    description: 'Raise dumbbells forward to shoulder height.',
    primary_muscles: ['Front Delts'], secondary_muscles: ['Upper Traps'],
    equipment: ['Dumbbell'], pro_tips: ['Keep slight bend in elbows; don\'t swing.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'pike_push_up', name: 'Pike Push-Up', category: 'push',
    description: 'Hips high in inverted V, lower head toward floor, press back up.',
    primary_muscles: ['Front Delts', 'Triceps'], secondary_muscles: ['Core'],
    equipment: ['Bodyweight'], pro_tips: ['Hips stay high throughout; head goes between hands.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'tricep_dip', name: 'Tricep Dip', category: 'push',
    description: 'Hands on bench behind, lower body by bending elbows, press back up.',
    primary_muscles: ['Triceps'], secondary_muscles: ['Chest', 'Front Delts'],
    equipment: ['Bench'], pro_tips: ['Keep elbows close; don\'t dip too deep if shoulders are sensitive.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'overhead_tricep_extension', name: 'Overhead Tricep Extension', category: 'push',
    description: 'Hold dumbbell overhead with both hands, lower behind head, extend back up.',
    primary_muscles: ['Triceps'], secondary_muscles: [],
    equipment: ['Dumbbell'], pro_tips: ['Keep elbows close to head; full stretch at bottom.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'close_grip_press', name: 'Close Grip Press', category: 'push',
    description: 'Narrow grip press emphasizing triceps over chest.',
    primary_muscles: ['Triceps', 'Chest'], secondary_muscles: ['Front Delts'],
    equipment: ['Barbell', 'Dumbbell'], pro_tips: ['Elbows tucked; wrists straight throughout.'],
    hasAnimation: true,
  },

  // ─── PULL UPPER/BACK (20) ───────────────────────────────────────────────────
  {
    exercise_id: 'pull_up', name: 'Pull-Up', category: 'pull',
    description: 'Overhand grip, pull chin above bar, lower with control.',
    primary_muscles: ['Lats', 'Biceps'], secondary_muscles: ['Rhomboids', 'Core'],
    equipment: ['Pullup Bar'], pro_tips: ['Full dead hang at bottom; initiate with scapular depression.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'chin_up', name: 'Chin-Up', category: 'pull',
    description: 'Underhand grip pull-up, more bicep involvement.',
    primary_muscles: ['Biceps', 'Lats'], secondary_muscles: ['Rhomboids'],
    equipment: ['Pullup Bar'], pro_tips: ['Supinate grip fully; think "elbows to hips".'],
    hasAnimation: true,
  },
  {
    exercise_id: 'neutral_grip_pull_up', name: 'Neutral Grip Pull-Up', category: 'pull',
    description: 'Palms facing each other, easier on shoulders.',
    primary_muscles: ['Lats', 'Biceps'], secondary_muscles: ['Rhomboids'],
    equipment: ['Pullup Bar'], pro_tips: ['Great for shoulder health; keep core tight.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'assisted_pull_up', name: 'Assisted Pull-Up', category: 'pull',
    description: 'Use band or machine assistance to complete pull-up range of motion.',
    primary_muscles: ['Lats', 'Biceps'], secondary_muscles: ['Rhomboids'],
    equipment: ['Pullup Bar', 'Band'], pro_tips: ['Use just enough assistance; progress by reducing help.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'inverted_row', name: 'Inverted Row', category: 'pull',
    description: 'Body under bar, pull chest to bar keeping body straight.',
    primary_muscles: ['Rhomboids', 'Lats'], secondary_muscles: ['Biceps', 'Core'],
    equipment: ['Pullup Bar', 'TRX'], pro_tips: ['Squeeze shoulder blades at top; keep body rigid.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'db_row', name: 'Dumbbell Row', category: 'pull',
    description: 'Bent over, one hand on bench, row dumbbell to hip.',
    primary_muscles: ['Lats', 'Rhomboids'], secondary_muscles: ['Biceps', 'Rear Delts'],
    equipment: ['Dumbbell', 'Bench'], pro_tips: ['Elbow drives back, not up; full stretch at bottom.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'single_arm_db_row', name: 'Single-Arm DB Row', category: 'pull',
    description: 'Unilateral row for balanced lat development.',
    primary_muscles: ['Lats', 'Rhomboids'], secondary_muscles: ['Biceps', 'Core'],
    equipment: ['Dumbbell'], pro_tips: ['Don\'t rotate torso; keep hips square.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'renegade_row', name: 'Renegade Row', category: 'pull',
    description: 'In push-up position on dumbbells, row one arm at a time.',
    primary_muscles: ['Lats', 'Core'], secondary_muscles: ['Rhomboids', 'Triceps'],
    equipment: ['Dumbbell'], pro_tips: ['Minimize hip rotation; wide foot stance helps.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'face_pull', name: 'Face Pull', category: 'pull',
    description: 'Pull cable/band to face level, elbows high, external rotation.',
    primary_muscles: ['Rear Delts', 'Mid Traps'], secondary_muscles: ['Rhomboids'],
    equipment: ['Cable', 'Band'], pro_tips: ['Elbows above wrists; think "show your biceps".'],
    hasAnimation: true,
  },
  {
    exercise_id: 'rear_delt_raise', name: 'Rear Delt Raise', category: 'pull',
    description: 'Bent over, raise dumbbells to sides targeting rear delts.',
    primary_muscles: ['Rear Delts'], secondary_muscles: ['Mid Traps', 'Rhomboids'],
    equipment: ['Dumbbell'], pro_tips: ['Slight internal rotation; lead with elbows.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'hammer_curl', name: 'Hammer Curl', category: 'pull',
    description: 'Neutral grip curl targeting brachialis and brachioradialis.',
    primary_muscles: ['Biceps', 'Brachialis'], secondary_muscles: ['Forearms'],
    equipment: ['Dumbbell'], pro_tips: ['Thumbs up throughout; don\'t swing.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'bicep_curl', name: 'Bicep Curl', category: 'pull',
    description: 'Supinated curl from full extension to full flexion.',
    primary_muscles: ['Biceps'], secondary_muscles: ['Brachialis', 'Forearms'],
    equipment: ['Dumbbell', 'Barbell'], pro_tips: ['Supinate at top; don\'t let elbows drift forward.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'concentration_curl', name: 'Concentration Curl', category: 'pull',
    description: 'Seated, elbow on inner thigh, curl for peak contraction.',
    primary_muscles: ['Biceps'], secondary_muscles: [],
    equipment: ['Dumbbell'], pro_tips: ['Full range; squeeze hard at top.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'preacher_curl', name: 'Preacher Curl', category: 'pull',
    description: 'Arm on preacher pad, curl from full extension.',
    primary_muscles: ['Biceps'], secondary_muscles: ['Brachialis'],
    equipment: ['Dumbbell', 'Barbell'], pro_tips: ['Don\'t hyperextend at bottom; control the eccentric.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'upright_row', name: 'Upright Row', category: 'pull',
    description: 'Pull bar/dumbbells up along body to chin level, elbows high.',
    primary_muscles: ['Side Delts', 'Upper Traps'], secondary_muscles: ['Biceps'],
    equipment: ['Barbell', 'Dumbbell'], pro_tips: ['Wide grip reduces shoulder impingement risk.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'lat_pulldown', name: 'Lat Pulldown', category: 'pull',
    description: 'Pull bar to upper chest, elbows drive down and back.',
    primary_muscles: ['Lats'], secondary_muscles: ['Biceps', 'Rhomboids'],
    equipment: ['Cable', 'Machine'], pro_tips: ['Slight lean back; initiate with lats not arms.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'band_pull_apart', name: 'Band Pull Apart', category: 'pull',
    description: 'Hold band at shoulder height, pull apart to full extension.',
    primary_muscles: ['Rear Delts', 'Rhomboids'], secondary_muscles: ['Mid Traps'],
    equipment: ['Band'], pro_tips: ['Keep arms straight; squeeze shoulder blades at end.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'dead_hang', name: 'Dead Hang', category: 'pull',
    description: 'Hang from bar with full body relaxed, building grip and shoulder health.',
    primary_muscles: ['Forearms', 'Lats'], secondary_muscles: ['Core'],
    equipment: ['Pullup Bar'], pro_tips: ['Breathe and relax; let spine decompress.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'scapular_pull_up', name: 'Scapular Pull-Up', category: 'pull',
    description: 'From dead hang, depress scapulae to lift body slightly without bending elbows.',
    primary_muscles: ['Lower Traps', 'Serratus'], secondary_muscles: ['Lats'],
    equipment: ['Pullup Bar'], pro_tips: ['Small movement; think "put shoulder blades in back pockets".'],
    hasAnimation: true,
  },
  {
    exercise_id: 'high_row', name: 'High Row', category: 'pull',
    description: 'Row with elbows high, targeting upper back and rear delts.',
    primary_muscles: ['Rear Delts', 'Upper Traps'], secondary_muscles: ['Rhomboids', 'Biceps'],
    equipment: ['Cable', 'Band'], pro_tips: ['Elbows above shoulders; squeeze at end range.'],
    hasAnimation: true,
  },

  // ─── CORE (20) ──────────────────────────────────────────────────────────────
  {
    exercise_id: 'plank', name: 'Plank', category: 'core',
    description: 'Hold straight body position on forearms and toes.',
    primary_muscles: ['Core'], secondary_muscles: ['Glutes', 'Shoulders'],
    equipment: ['Bodyweight'], pro_tips: ['Squeeze glutes and quads; breathe steadily.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'side_plank', name: 'Side Plank', category: 'core',
    description: 'Lateral plank on one forearm, hips elevated.',
    primary_muscles: ['Obliques'], secondary_muscles: ['Core', 'Glutes'],
    equipment: ['Bodyweight'], pro_tips: ['Stack feet or stagger for balance; keep hips high.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'hollow_hold', name: 'Hollow Hold', category: 'core',
    description: 'Lower back pressed to floor, legs extended, arms overhead, hold tight.',
    primary_muscles: ['Core'], secondary_muscles: ['Hip Flexors'],
    equipment: ['Bodyweight'], pro_tips: ['If low back lifts, regress immediately.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'dead_bug', name: 'Dead Bug', category: 'core',
    description: 'On back, extend opposite arm/leg without losing low-back contact.',
    primary_muscles: ['Core'], secondary_muscles: ['Hip Flexors'],
    equipment: ['Bodyweight'], pro_tips: ['Exhale as limb extends; keep ribs down.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'hanging_leg_raise', name: 'Hanging Leg Raise', category: 'core',
    description: 'Hang, raise straight legs, control down without swinging.',
    primary_muscles: ['Lower Abs'], secondary_muscles: ['Hip Flexors', 'Forearms'],
    equipment: ['Pullup Bar'], pro_tips: ['Slight curl at top increases ab emphasis.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'hanging_knee_raise', name: 'Hanging Knee Raise', category: 'core',
    description: 'Hang, lift knees toward chest, control down.',
    primary_muscles: ['Lower Abs'], secondary_muscles: ['Hip Flexors'],
    equipment: ['Pullup Bar'], pro_tips: ['Exhale at top; keep shoulders active.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'lying_leg_raise', name: 'Lying Leg Raise', category: 'core',
    description: 'On back, legs straight, lift and lower without arching low back.',
    primary_muscles: ['Lower Abs'], secondary_muscles: ['Hip Flexors'],
    equipment: ['Bodyweight'], pro_tips: ['Stop lowering before low back lifts.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'reverse_crunch', name: 'Reverse Crunch', category: 'core',
    description: 'Curl pelvis up bringing knees toward chest, lower slowly.',
    primary_muscles: ['Lower Abs'], secondary_muscles: [],
    equipment: ['Bodyweight'], pro_tips: ['Think "roll pelvis" not "swing legs".'],
    hasAnimation: false,
  },
  {
    exercise_id: 'russian_twist', name: 'Russian Twist', category: 'core',
    description: 'Sit with torso leaned back, rotate shoulders side to side.',
    primary_muscles: ['Obliques'], secondary_muscles: ['Core'],
    equipment: ['Bodyweight', 'Dumbbell', 'Kettlebell'], pro_tips: ['Rotate ribs/shoulders, not just arms.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'bicycle_crunch', name: 'Bicycle Crunch', category: 'core',
    description: 'Alternate elbow-to-opposite-knee with controlled rotation.',
    primary_muscles: ['Obliques', 'Upper Abs'], secondary_muscles: ['Hip Flexors'],
    equipment: ['Bodyweight'], pro_tips: ['Keep low back close to floor; don\'t yank neck.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'mountain_climber', name: 'Mountain Climber', category: 'core',
    description: 'High plank, alternate driving knees forward at steady pace.',
    primary_muscles: ['Core'], secondary_muscles: ['Hip Flexors', 'Front Delts'],
    equipment: ['Bodyweight'], pro_tips: ['Keep shoulders over wrists; hips low and stable.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'v_up', name: 'V-Up', category: 'core',
    description: 'Simultaneously raise legs and torso to meet at top.',
    primary_muscles: ['Upper Abs', 'Lower Abs'], secondary_muscles: ['Hip Flexors'],
    equipment: ['Bodyweight'], pro_tips: ['Exhale at top; keep movement smooth.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'toe_touch_crunch', name: 'Toe-Touch Crunch', category: 'core',
    description: 'Legs up, reach hands toward toes by curling upper back.',
    primary_muscles: ['Upper Abs'], secondary_muscles: [],
    equipment: ['Bodyweight'], pro_tips: ['Small controlled curl; avoid swinging arms.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'flutter_kick', name: 'Flutter Kick', category: 'core',
    description: 'On back, alternate small kicks with legs extended while bracing abs.',
    primary_muscles: ['Lower Abs'], secondary_muscles: ['Hip Flexors'],
    equipment: ['Bodyweight'], pro_tips: ['Hands under hips if low back complains.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'ab_rollout', name: 'Ab Rollout', category: 'core',
    description: 'Roll forward keeping ribs down, return by bracing abs and lats.',
    primary_muscles: ['Core'], secondary_muscles: ['Lats', 'Front Delts'],
    equipment: ['Machine', 'Barbell'], pro_tips: ['Don\'t let low back sag; keep posterior pelvic tilt.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'cable_crunch', name: 'Cable Crunch', category: 'core',
    description: 'Kneel, crunch ribs toward pelvis against cable tension.',
    primary_muscles: ['Upper Abs'], secondary_muscles: [],
    equipment: ['Cable'], pro_tips: ['Focus on spine flexion, not hip hinge.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'bird_dog', name: 'Bird Dog', category: 'core',
    description: 'On all fours, extend opposite arm and leg, hold, alternate.',
    primary_muscles: ['Core'], secondary_muscles: ['Erectors', 'Glutes'],
    equipment: ['Bodyweight'], pro_tips: ['Keep hips square; imagine balancing a glass on your back.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'superman_hold', name: 'Superman Hold', category: 'core',
    description: 'Prone, lift arms and legs slightly, hold with glutes and back engaged.',
    primary_muscles: ['Erectors'], secondary_muscles: ['Glutes'],
    equipment: ['Bodyweight'], pro_tips: ['Small lift is enough; avoid cranking neck.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'side_plank_reach', name: 'Side Plank Reach', category: 'core',
    description: 'From side plank, reach top arm under body then open back up.',
    primary_muscles: ['Obliques'], secondary_muscles: ['Core', 'Rear Delts'],
    equipment: ['Bodyweight'], pro_tips: ['Move from thoracic spine; keep hips elevated.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'woodchopper', name: 'Woodchopper', category: 'core',
    description: 'Rotate torso diagonally across body under tension.',
    primary_muscles: ['Obliques'], secondary_muscles: ['Core'],
    equipment: ['Cable', 'Band', 'Dumbbell'], pro_tips: ['Rotate ribs, keep hips mostly stable.'],
    hasAnimation: false,
  },

  // ─── CONDITIONING / FULL BODY (20) ──────────────────────────────────────────
  {
    exercise_id: 'burpee', name: 'Burpee', category: 'conditioning',
    description: 'Squat down, jump to plank, optional push-up, jump feet in, stand/jump.',
    primary_muscles: ['Full Body'], secondary_muscles: ['Quads', 'Core', 'Chest'],
    equipment: ['Bodyweight'], pro_tips: ['Keep pace sustainable; quality over chaos.'],
    hasAnimation: true,
  },
  {
    exercise_id: 'squat_jump', name: 'Squat Jump', category: 'conditioning',
    description: 'Squat then jump vertically, land softly and repeat.',
    primary_muscles: ['Quads', 'Glutes'], secondary_muscles: ['Calves'],
    equipment: ['Bodyweight'], pro_tips: ['Land quietly; knees track over toes.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'lunge_jump', name: 'Jump Lunge', category: 'conditioning',
    description: 'Split stance, jump and switch legs in air, land softly.',
    primary_muscles: ['Quads', 'Glutes'], secondary_muscles: ['Calves', 'Core'],
    equipment: ['Bodyweight'], pro_tips: ['Keep torso tall; don\'t slam the landing.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'skater_jump', name: 'Skater Jump', category: 'conditioning',
    description: 'Lateral bound from one foot to the other, stick landing.',
    primary_muscles: ['Glutes', 'Abductors'], secondary_muscles: ['Quads', 'Core'],
    equipment: ['Bodyweight'], pro_tips: ['Knee stays aligned; don\'t collapse inward.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'box_jump', name: 'Box Jump', category: 'conditioning',
    description: 'Jump onto box, land softly, step down safely.',
    primary_muscles: ['Glutes', 'Quads'], secondary_muscles: ['Calves'],
    equipment: ['Box'], pro_tips: ['Step down, don\'t jump down for repeat volume.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'high_knees', name: 'High Knees', category: 'conditioning',
    description: 'Run in place driving knees up, keep posture tall.',
    primary_muscles: ['Full Body'], secondary_muscles: ['Hip Flexors', 'Calves', 'Core'],
    equipment: ['Bodyweight'], pro_tips: ['Stay light on feet; keep shoulders relaxed.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'butt_kicks', name: 'Butt Kicks', category: 'conditioning',
    description: 'Run in place kicking heels toward glutes.',
    primary_muscles: ['Full Body'], secondary_muscles: ['Hamstrings', 'Calves'],
    equipment: ['Bodyweight'], pro_tips: ['Keep knees pointing down; don\'t arch back.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'battle_rope_wave', name: 'Battle Rope Waves', category: 'conditioning',
    description: 'Create alternating rope waves with athletic stance.',
    primary_muscles: ['Full Body'], secondary_muscles: ['Front Delts', 'Core', 'Forearms'],
    equipment: ['Battle Rope'], pro_tips: ['Breathe rhythmically; keep ribs down.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'kb_clean', name: 'Kettlebell Clean', category: 'conditioning',
    description: 'Hinge and drive hips to bring kettlebell to rack position.',
    primary_muscles: ['Glutes', 'Hamstrings'], secondary_muscles: ['Core', 'Forearms'],
    equipment: ['Kettlebell'], pro_tips: ['Keep bell close; rotate around hand, not over it.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'kb_snatch', name: 'Kettlebell Snatch', category: 'conditioning',
    description: 'From swing/clean path, punch kettlebell overhead into lockout.',
    primary_muscles: ['Glutes', 'Hamstrings'], secondary_muscles: ['Front Delts', 'Core'],
    equipment: ['Kettlebell'], pro_tips: ['Lock ribs down overhead; avoid over-arching.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'db_thruster', name: 'Dumbbell Thruster', category: 'conditioning',
    description: 'Front rack dumbbells, squat then drive to overhead press in one motion.',
    primary_muscles: ['Quads', 'Front Delts'], secondary_muscles: ['Glutes', 'Triceps'],
    equipment: ['Dumbbell'], pro_tips: ['Use legs to start the press; keep elbows up in rack.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'clean_and_press', name: 'Clean and Press', category: 'conditioning',
    description: 'Clean weight to rack then press overhead.',
    primary_muscles: ['Glutes', 'Front Delts'], secondary_muscles: ['Hamstrings', 'Triceps'],
    equipment: ['Kettlebell', 'Dumbbell', 'Barbell'], pro_tips: ['Brace before press; keep wrist stacked.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'farmer_carry', name: 'Farmer Carry', category: 'conditioning',
    description: 'Walk holding weights at sides with tall posture.',
    primary_muscles: ['Forearms', 'Core'], secondary_muscles: ['Upper Traps', 'Glutes'],
    equipment: ['Dumbbell', 'Kettlebell'], pro_tips: ['Ribs down, chin neutral; don\'t let shoulders creep up.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'suitcase_carry', name: 'Suitcase Carry', category: 'conditioning',
    description: 'Carry weight on one side, resist leaning.',
    primary_muscles: ['Obliques', 'Core'], secondary_muscles: ['Forearms', 'Glutes'],
    equipment: ['Dumbbell', 'Kettlebell'], pro_tips: ['Stay tall; imagine balancing a book on your head.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'bear_crawl', name: 'Bear Crawl', category: 'conditioning',
    description: 'Hands and feet on floor, knees hover, crawl with tight core.',
    primary_muscles: ['Core'], secondary_muscles: ['Front Delts', 'Quads'],
    equipment: ['Bodyweight'], pro_tips: ['Small steps; keep hips low and stable.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'crab_walk', name: 'Crab Walk', category: 'conditioning',
    description: 'Hands behind, hips up, walk keeping glutes engaged.',
    primary_muscles: ['Triceps', 'Glutes'], secondary_muscles: ['Core', 'Rear Delts'],
    equipment: ['Bodyweight'], pro_tips: ['Keep fingers pointing away if wrists allow; move smoothly.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'sled_push', name: 'Sled Push', category: 'conditioning',
    description: 'Drive sled forward with strong knee and hip extension.',
    primary_muscles: ['Quads', 'Glutes'], secondary_muscles: ['Calves', 'Core'],
    equipment: ['Sled'], pro_tips: ['Short powerful steps; keep spine neutral.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'sled_pull', name: 'Sled Pull', category: 'conditioning',
    description: 'Pull sled backward or via strap with steady steps.',
    primary_muscles: ['Hamstrings', 'Glutes'], secondary_muscles: ['Quads', 'Core'],
    equipment: ['Sled'], pro_tips: ['Keep hips down and steps consistent; avoid rounding.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'rowing_machine', name: 'Rowing Machine', category: 'conditioning',
    description: 'Drive with legs, hinge, pull handle to ribs, reverse smoothly.',
    primary_muscles: ['Full Body'], secondary_muscles: ['Lats', 'Quads', 'Glutes'],
    equipment: ['Rowing Machine'], pro_tips: ['Legs first, then hips, then arms; reverse on return.'],
    hasAnimation: false,
  },
  {
    exercise_id: 'jump_rope', name: 'Jump Rope', category: 'conditioning',
    description: 'Small quick jumps, wrists turn rope, keep posture tall.',
    primary_muscles: ['Full Body'], secondary_muscles: ['Calves', 'Core'],
    equipment: ['Jump Rope'], pro_tips: ['Jump low; let wrists do the work, not shoulders.'],
    hasAnimation: false,
  },
];

export const EXERCISE_MAP = new Map<string, ExerciseInfo>(
  EXERCISES.map(e => [e.exercise_id, e])
);

export function getExercise(id: string): ExerciseInfo | undefined {
  return EXERCISE_MAP.get(id);
}

export const CATEGORY_CONFIG: Record<ExerciseCategory, { label: string; color: string; emoji: string }> = {
  lower: { label: 'Lower Body', color: '#34C759', emoji: '🟢' },
  push: { label: 'Push', color: '#007AFF', emoji: '🔵' },
  pull: { label: 'Pull', color: '#AF52DE', emoji: '🟣' },
  core: { label: 'Core', color: '#FF9500', emoji: '🟡' },
  conditioning: { label: 'Conditioning', color: '#FF3B30', emoji: '🟠' },
};
