/**
 * Terms — Terms of Service page
 */

import Footer from '@/components/Footer';
import SiteLogo from '@/components/SiteLogo';

const LAST_UPDATED = 'March 8, 2026';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h3 className="text-lg font-bold text-[#1D1D1F] mb-3">{title}</h3>
      <div className="text-[#3C3C43] leading-relaxed space-y-3 text-sm">{children}</div>
    </div>
  );
}

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#F5F5F7] flex flex-col">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-xl border-b border-[#F0F0F5] sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-5 py-4 flex items-center justify-between">
          <SiteLogo size={36} />
          <a href="/" className="text-sm text-[#007AFF] font-medium hover:opacity-70 transition-opacity">
            ← Back
          </a>
        </div>
      </header>

      <main className="flex-1 max-w-3xl mx-auto w-full px-5 py-12">
        <div className="mb-10">
          <h2 className="text-4xl font-bold text-[#1D1D1F] tracking-tight mb-3">Terms of Service</h2>
          <p className="text-sm text-[#8E8E93]">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="bg-white rounded-3xl p-8 shadow-[0_2px_20px_rgba(0,0,0,0.06)]">
          <Section title="Acceptance of Terms">
            <p>
              By accessing or using PromptFit ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </Section>

          <Section title="Description of Service">
            <p>
              PromptFit is a workout compiler and renderer that integrates with ChatGPT via a GPT Action. The Service allows users to generate structured workout plans and render them as interactive, animated workout sessions accessible via a unique URL.
            </p>
          </Section>

          <Section title="Use of the Service">
            <p>You may use PromptFit for personal, non-commercial fitness purposes. You agree not to:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li>Use the API to submit abusive, harmful, or illegal content</li>
              <li>Attempt to overload, disrupt, or reverse-engineer the Service</li>
              <li>Use automated scripts to submit excessive API requests</li>
              <li>Misrepresent the source or nature of workout plans submitted to the API</li>
            </ul>
          </Section>

          <Section title="API Usage">
            <p>
              The PromptFit API (<code className="bg-[#F5F5F7] px-1 rounded font-mono text-xs">POST /api/get-plan-id</code>) is provided as-is for integration with GPT Actions and personal use. We reserve the right to rate-limit, restrict, or terminate API access at any time without notice.
            </p>
            <p>
              Workout plans submitted to the API are cached for 30 days. We do not guarantee the availability or persistence of any specific plan URL beyond this period.
            </p>
          </Section>

          <Section title="Health and Fitness Disclaimer">
            <p>
              <strong className="text-[#1D1D1F]">PromptFit is not a medical service.</strong> The workout plans generated by GPT and rendered by PromptFit are for general fitness purposes only and are not a substitute for professional medical advice, diagnosis, or treatment.
            </p>
            <p>
              Before beginning any exercise program, consult with a qualified healthcare professional, especially if you have any pre-existing medical conditions, injuries, or health concerns. You exercise at your own risk.
            </p>
            <p>
              We are not responsible for any injury, illness, or adverse outcome resulting from the use of workout plans generated or rendered by PromptFit.
            </p>
          </Section>

          <Section title="Intellectual Property">
            <p>
              The PromptFit application, including its design, exercise animations, and source code, is the property of PromptFit and its creators. Exercise IDs and workout plan structures submitted via the API remain the property of the submitter.
            </p>
          </Section>

          <Section title="Limitation of Liability">
            <p>
              To the maximum extent permitted by applicable law, PromptFit and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to physical injury, data loss, or service interruption.
            </p>
          </Section>

          <Section title="Availability">
            <p>
              We strive to keep PromptFit available but do not guarantee uninterrupted access. We may modify, suspend, or discontinue the Service at any time without notice.
            </p>
          </Section>

          <Section title="Changes to These Terms">
            <p>
              We may update these Terms of Service from time to time. The "Last updated" date at the top of this page reflects the most recent revision. Continued use of PromptFit after changes constitutes acceptance of the updated terms.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              If you have questions about these Terms of Service, please reach out via the PromptFit GitHub repository or the contact information provided in the app.
            </p>
          </Section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
